### ISSUE TITLE
Creation of a UI/UX Prototype for the Client Interface (Input Parsing)

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#16]
## Description

Based on the decision made in #11, create an input interface for the reading and uploading of the files. The developers chose to develop with React. A protopyte should be implemented with Yarn to create a React project.  

## Acceptance

Please describe what is necessary for this ticket to count as resolved. You do not need to repeat the definition-of-done that your team has agreed on generally.

- [x] #21
- [x] Prototype of the landing page and Input parsing of the React, as chosen in #11 
- [x] #22
- [ ] Form is sent to the server implemented in #14 

## Definition of Ready

If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by MarkusHenkel** [comment]
Tasks:
1. The Sketch can be found at https://github.com/Integrative-Transcriptomics/tss-prediction-comparison/wiki/Input%E2%80%90Interface-Concept 
2. & 3. Prototype can be found on branch 22-Implementation-of-a-Client-Side-interface-for-File-Uploading in ./tss-prediction-comparison/my-react-app-kopie 
4. Not finished 

Further improvements:
1. Being able to remove conditions if you clicked on the + by accident (Done)
2. Descriptions of the buttons by hovering over them (i.e. "Add a second/third/etc. condition" on the +)
4. Stretch content of the website to the screen size to avoid half of the screen being black
5. Only the file uploaded most recently is shown (Done)
6. Instead of having to write how many replicates, the website could just count all the files the user uploaded and display them under "Replicates:" 
7. Button for removing added files (Done)
8. Error message "too many replicates" is inconsisten: selecting files one by one circumvents the error message completely, selecting multiple files at once results doesnt always result in a error message

Problem: Opening the local host worked for Gregor locally, I needed an extra file (package.json) that I added and pushed, it doesnt work for Jannik as of now.
Update for future issues: Fully deleting all local files and pulling everything anew fixed Jannik's issue.
