### ISSUE TITLE
TSS prediction

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#2]
## Description
As a biologist, I want to predict TSS sites based on RNA-seq data in order to identify the start of expressed genes.

## Acceptance
_Remember: Definition of DONE_

- [x] #33
- [x] #34
- [x] #35

## Definition of Ready
If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by AronWichtner** [comment]
### Review:

I reviewed methods in OperationsOnWiggle.py, Model_Training.ipynb, tssPredictor.py


### Wiki entry:
Your wiki entry has a good structure and guides the reader very well through the process and background information of the prediction.

### Code:

- Readability: The code is readable and you used fitting names for methods and variables. Here and there the code is bit redundant and thus gets a bit long for one method. 

- Style: The coding style fits to our conventions. Here there some blank lines are missing (f.e. in JobObject.py)

- Functionality: I think the code implements very well what was written in the wiki entry and the different steps make sense when reading through it. Since i am not to familiar in this field and can not say much about logical errors. As the Issue states the TSS are reported in form of a table (dataFrame). This was solved by Amelie in #29 

- Testing: As you mentioned in your wiki entry: "aswell as the fact that there is no true gold standard data set of ground truths that can be used to evaluate the performance of single component algorithms, aswell as the full algorithm". Besides that we now rely on MasterTable data which has one or multiple conditions. As far as i understood the MasterTable the model was trained with does not have conditions. Maybe this will lead to problems?

- Documentation: most methods have internal documentation which helps understanding the code but some are missing it, especially in JobObject.py and tssPredictor.py.
