### ISSUE TITLE
Parsing TSSpredator's MasterTable

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#28]
## Description
We want to quantify how accurate the newly developed method is when compared to an established method, such as TSSpredator. For this, the user should be able to upload a Master Table and get different parameters of the prediction. Not all columns might be needed for the comparison.

## Acceptance

- [x] The user is able to upload a MasterTable from the client side
- [x] The MasterTable is parsed in the back-end and the needed information is extracted. 
- [x] The information is passed for the comparison in a well-defined data structure.

**Comment by mwittep** [comment]
@AronWichtner, as discussed more detailed information. 

As discussed today, we need the position and the strand of each TSS. It suffices if we extract the enriched TSS, but detected TSSs are also ok. 

We would then need the condition column (to compare the correct conditions to one another), as well as the class. 

From the binary classification, we could produce a class label instead of having a new row per TSS.

**Comment by AronWichtner** [comment]
### This Issue is solved on Branch 28-parsing-MasterTable


## The user is able to upload a MasterTable from the client side .
(Done by Julian and Front end Team)

## The MasterTable is parsed in the back-end and the needed information is extracted.

### The MasterTable is parsed to a DataFrame the following way:  

- for each condition in the MasterTable a DataFrame is created, which only holds the positions, which were matched to that specific condition
- only keep detected Positions
- the binary TSS classification is exchanged with a labeling-system; The DataFrames have a "TSS type " column in which a TSS class (String) is matched to every position
- only keep relevant rows: "Pos", "Strand", "TSS_type"

## The information is passed for the comparison in a well-defined data structure.

- the method "parse_master_table" returns a dictionary in which the keys represent the conditions of the MasterTable and the values represent the corresponding DataFrames.


### The Code has internal Documentation and is tested

**Comment by AmelieFl** [comment]
Review:

- Readability: Da du viele kleine Hilfsfunktionen geschrieben hast ist der Code gut strukturiert und einfach zu verstehen
- Functionality: Die unit tests laufen durch, es scheint alles so zu funktionieren wie es soll. Ich habe die tss typen bei der Klassifizierung etwas anders benannt. Das könnte dann zu Problemen beim Vergleich von prediction und mastertable führen. Wir können uns ja am Montag auf eine einheitliche Benennung einigen.
- Style: die vereinbarten coding convetions wurden eingehalten
- Performance: die funktion __drop_rows_with_unwanted_conditions sieht für mich unnötig kompliziert aus. Wenn ich da nicht etwas übersehe könnte man sie durch:    
filtered_df = data_frame[data_frame["Condition"] == condition].copy()
return filtered_df 
ersetzten, was deutlich effizienter ist
- Code Comments: alle Funktionen sind ausführlich dokumentiert

**Comment by AronWichtner** [comment]
Hi Amelie,

i refactored the __drop_rows_with_unwanted_conditions and also the __delete_not_detected_positions according to your ideas.
The performance is now a lot better.
