### ISSUE TITLE
Given one or multiple wiggle files, the program is able to predict putative transcription start sites.

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#34]

**Comment by AronWichtner** [comment]
This Issue was partly solved in #2 

### Review:

- a review for the prediction itself has already been made in #2 

- user can upload multiple conditions with multiple technical replicas -> each conditions is processed as a Job and but in jobQueue -> technical replicas are summarized -> TSS for each condition are predicted

- Readability: Following this pipeline in the code might not be easy for someone who does not know the code. Especially the method upload_file() in server.py is very long and thus very hard to read. It might help to document how jobs are added and started. Besides that i think the Issue was solved very well.
